# Generated by Django 2.1.7 on 2019-03-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmate', '0002_auto_20190318_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolm',
            name='schoolname',
            field=models.CharField(max_length=50, verbose_name='校名'),
        ),
    ]
