# Generated by Django 2.1.7 on 2019-03-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classmate', '0003_auto_20190318_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='p_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='classmate.classUser', verbose_name='用户id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='p_name',
            field=models.CharField(max_length=50, verbose_name='用户姓名'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='sex',
            field=models.CharField(choices=[(1, '男'), (2, '女')], max_length=50),
        ),
    ]
