# Generated by Django 2.1.7 on 2019-03-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmate', '0005_auto_20190318_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='用户电话'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='sex',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], max_length=50),
        ),
    ]
