# Generated by Django 2.1.7 on 2019-03-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmate', '0007_auto_20190318_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_type',
            field=models.CharField(choices=[('1', '动态'), ('2', '技术文章'), ('3', '难题')], max_length=50),
        ),
    ]
