# Generated by Django 2.1.7 on 2019-03-19 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classmate', '0008_auto_20190318_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='god',
            old_name='classid',
            new_name='classNo',
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classmate.classUser', verbose_name='用户账号'),
        ),
    ]
