# Generated by Django 2.1.7 on 2019-03-19 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classmate', '0009_auto_20190319_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='p_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classmate.classUser', verbose_name='用户姓名'),
        ),
    ]
